name: Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
      - uses: coursier/cache-action@v3
      - name: publish
        run: |
          cat .publish_sbt >> build.sbt
          ./sbt +publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

