name: Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v2
        with:
          java-version: zulu@1.8
      - uses: coursier/cache-action@v5
      - name: publish
        run: |
          cat .publish_github >> build.sbt
          csbt +publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

